// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuI1DbRuGvgN5k93SbXU0hqpdk99gT540',
    appId: '1:589777838243:web:e9bca5ed0c57b296779f16',
    messagingSenderId: '589777838243',
    projectId: 'nichrome-final',
    authDomain: 'nichrome-final.firebaseapp.com',
    storageBucket: 'nichrome-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qS1wtbuqkJafRcVfxUyW2SpQ8QNY6ls',
    appId: '1:589777838243:android:793cac3c651fdf11779f16',
    messagingSenderId: '589777838243',
    projectId: 'nichrome-final',
    storageBucket: 'nichrome-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLJzyK__faiw5_2M34kKJxRb0evhfC5D8',
    appId: '1:589777838243:ios:aca7771083121ea6779f16',
    messagingSenderId: '589777838243',
    projectId: 'nichrome-final',
    storageBucket: 'nichrome-final.appspot.com',
    iosClientId: '589777838243-gj3mgrdnbt21bt5np7vq0laeap6oom8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.nichromeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLJzyK__faiw5_2M34kKJxRb0evhfC5D8',
    appId: '1:589777838243:ios:aca7771083121ea6779f16',
    messagingSenderId: '589777838243',
    projectId: 'nichrome-final',
    storageBucket: 'nichrome-final.appspot.com',
    iosClientId: '589777838243-gj3mgrdnbt21bt5np7vq0laeap6oom8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.nichromeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuI1DbRuGvgN5k93SbXU0hqpdk99gT540',
    appId: '1:589777838243:web:f32c04b8037da551779f16',
    messagingSenderId: '589777838243',
    projectId: 'nichrome-final',
    authDomain: 'nichrome-final.firebaseapp.com',
    storageBucket: 'nichrome-final.appspot.com',
  );

}